// Academics & Courses APIs
export { academicsApi } from './academicsApi';
export type {
  Course,
  Subject,
  Class,
  Curriculum,
  ClassEnrollment,
  AcademicCalendar,
  TermBreak,
  ExamEvent,
  ClassroomResource,
} from './academicsApi';
export {
  useListCoursesQuery,
  useGetCourseQuery,
  useCreateCourseMutation,
  useUpdateCourseMutation,
  useDeleteCourseMutation,
  useListSubjectsQuery,
  useGetSubjectQuery,
  useGetSubjectsByFacultyQuery,
  useCreateSubjectMutation,
  useUpdateSubjectMutation,
  useDeleteSubjectMutation,
  useListClassesQuery,
  useGetClassQuery,
  useCreateClassMutation,
  useUpdateClassMutation,
  useDeleteClassMutation,
  useListCurriculaQuery,
  useGetCurriculumQuery,
  useGetCurriculumByClassQuery,
  useCreateCurriculumMutation,
  useUpdateCurriculumMutation,
  useGetClassEnrollmentsQuery,
  useEnrollStudentInClassMutation,
  useUpdateEnrollmentStatusMutation,
  useRemoveEnrollmentMutation,
  useListAcademicCalendarsQuery,
  useGetAcademicCalendarQuery,
  useGetCurrentAcademicCalendarQuery,
  useCreateAcademicCalendarMutation,
  useUpdateAcademicCalendarMutation,
  useListResourcesQuery,
  useGetResourcesByClassQuery,
  useCreateResourceMutation,
  useUpdateResourceMutation,
  useDeleteResourceMutation,
} from './academicsApi';
